stages:
  - build
  - deploy
  - error
build:
  stage: build
  script:
    - export userFromGitlab=$GITLAB_USER_NAME
    - echo $usernameFromGitlab

    - yarn
    - yarn build

    - cp -R /opt/ci/front_kube_queue_ci.py .
    - cp -R /opt/ci/builder.sh .
    - cp -R /opt/script/update_version.py .

    - python3 front_kube_queue_ci.py build js yarn no $CI_PROJECT_NAME $CI_COMMIT_REF_NAME $GITLAB_USER_NAME $CI_COMMIT_SHA

    - sudo ./builder.sh

  tags:
    - build
deploy:
  stage: deploy
  script:
    - echo "Deploy"
    - export userFromGitlab=$GITLAB_USER_NAME
    - echo $usernameFromGitlab

    - cp -R /opt/ci/front_kube_queue_ci.py .

    - python3 front_kube_queue_ci.py deploy js yarn no $CI_PROJECT_NAME $CI_COMMIT_REF_NAME $GITLAB_USER_NAME $CI_COMMIT_SHA

  tags:
    - deploy
error:
  stage: error
  script:
    - echo "Failed"
    - sudo python3 /opt/ci/notify_front.py ❌  $CI_PROJECT_NAME  $CI_PROJECT_URL  $CI_COMMIT_REF_NAME  $GITLAB_USER_NAME $CI_PIPELINE_URL

  when: on_failure
  tags:
    - error
