import { createUseStyles } from 'react-jss'

export const useStyles = createUseStyles(() => ({
  wrapper: ({ hasStatus }) => ({
    display: 'flex',
    flexDirection: 'column',
    padding: '0 8px',
    opacity: hasStatus ? 1 : 0,
    transition: 'all .5s ease',
  }),
  progressBlock: {
    display: 'flex',
    flexDirection: 'column',
    background: '#F5F5F5',
    borderRadius: 8,
    marginBottom: 2,
    padding: 16,
  },
  imgWrapper: {
    display: 'flex',
    justifyContent: 'center',
    position: 'relative',
    height: 40,
  },
  img: {
    position: 'absolute',
    left: -16,
    top: 0,
    minWidth: 40,
    maxWidth: 40,
    height: 40,
    boxShadow: '0px 1px 4px rgba(0, 0, 0, 0.2)',
    border: '2px solid #FFFFFF',
    boxSizing: 'border-box',
    borderRadius: '50%',
    objectFit: 'cover',
  },
  progressBar: {
    display: 'flex',
    marginTop: 4,
    background: 'rgba(33, 33, 33, 0.1)',
    borderRadius: 16,
    minHeight: 8,
    maxHeight: 8,
    position: 'relative',
  },
  progressBarFill: {
    position: 'absolute',
    top: 0,
    left: 0,
    background: 'linear-gradient(90deg, #7B4DFB 0%, #4D77FB 100%)',
    borderRadius: 16,
    minHeight: 8,
    maxHeight: 8,
  },
  infoWrapper: {
    display: 'flex',
    flexDirection: 'column',
    marginTop: 8,
  },
  progressInfo: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  yourProgress: {
    color: '#4D77FB',
    fontSize: 12,
    lineHeight: '14px',
    fontWeight: 500,
  },
  status: {
    fontWeight: 500,
    fontSize: 15,
    lineHeight: '18px',
    letterSpacing: -0.24,
  },
  remainInfo: {
    display: 'flex',
    justifyContent: 'flex-end',
    fontSize: 12,
    lineHeight: '14px',
  },
}))
